package tiendas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import tiendas.User;
import java.util.*;

public class Factura extends javax.swing.JFrame {

    String buscar;
    String seleccion1;
    String seleccion2;
    String seleccion3;
    String seleccion4;
    String seleccion5;

    int c1, c2, c3, c4, c5, num;
    double vtotal;
    String updateQuery;
    double valiv, valnet, valica, valrete;
    User user = new User();
    Conex Con1 = new Conex();
    Connection conet;
    Statement st;
    ResultSet rs;
    Random rand = new Random();
    int exi;

    public Factura() {
        initComponents();
        this.setLocationRelativeTo(null);
        Numfatura();
        num = rand.nextInt(9);
        random.setText("" + num);
        iniciarCombobox();

        this.txtNombre.setText(user.usuario);
        SpinnerNumberModel model1 = new SpinnerNumberModel(0, 0, 100, 1);
        SpinnerNumberModel model2 = new SpinnerNumberModel(0, 0, 100, 1);
        SpinnerNumberModel model3 = new SpinnerNumberModel(0, 0, 100, 1);
        SpinnerNumberModel model4 = new SpinnerNumberModel(0, 0, 100, 1);
        SpinnerNumberModel model5 = new SpinnerNumberModel(0, 0, 100, 1);
        SpinnerNumberModel model6 = new SpinnerNumberModel(0, 0, 100, 1);
        SpinnerNumberModel model7 = new SpinnerNumberModel(0, 0, 100, 1);
        SpinnerNumberModel model8 = new SpinnerNumberModel(0, 0, 100, 1);
        SpinnerNumberModel model9 = new SpinnerNumberModel(0, 0, 100, 1);
        SpinnerNumberModel model10 = new SpinnerNumberModel(0, 0, 100, 1);

        jSpinner1.setModel(model1);
        jSpinner2.setModel(model2);
        jSpinner3.setModel(model3);
        jSpinner4.setModel(model4);
        jSpinner5.setModel(model5);

        actuDatosFac();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtResp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtArt1 = new javax.swing.JTextField();
        txtArt2 = new javax.swing.JTextField();
        txtArt3 = new javax.swing.JTextField();
        txtArt4 = new javax.swing.JTextField();
        txtArt5 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        total1 = new javax.swing.JTextField();
        total2 = new javax.swing.JTextField();
        total3 = new javax.swing.JTextField();
        total4 = new javax.swing.JTextField();
        total5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        valNet = new javax.swing.JTextField();
        valIva = new javax.swing.JTextField();
        valTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        icalabel = new javax.swing.JLabel();
        ReteFuente = new javax.swing.JLabel();
        txtICA = new javax.swing.JTextField();
        txtRete = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        factura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        random = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Factura"));

        jLabel1.setText("NIT");

        txtNit.setEditable(false);
        txtNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitActionPerformed(evt);
            }
        });

        jLabel2.setText("Responsable");

        txtResp.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Items"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        txtArt1.setEditable(false);

        txtArt2.setEditable(false);

        txtArt3.setEditable(false);

        txtArt4.setEditable(false);

        txtArt5.setEditable(false);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });

        total1.setEditable(false);
        total1.setText("0");

        total2.setEditable(false);
        total2.setText("0");

        total3.setEditable(false);
        total3.setText("0");

        total4.setEditable(false);
        total4.setText("0");

        total5.setEditable(false);
        total5.setText("0");
        total5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad");

        jLabel7.setText("Total");

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner3StateChanged(evt);
            }
        });

        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner4StateChanged(evt);
            }
        });

        jSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner5StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtArt5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(txtArt4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArt3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArt2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArt1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(total3)
                    .addComponent(total4)
                    .addComponent(total5)
                    .addComponent(total1)
                    .addComponent(total2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));

        valNet.setEditable(false);

        valIva.setEditable(false);

        valTotal.setEditable(false);
        valTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valTotalActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor Neto");

        jLabel4.setText("IVA");

        jLabel5.setText("TOTAL");

        jLabel12.setText("descuento");

        txtDesc.setEditable(false);

        icalabel.setText("ICA");

        ReteFuente.setText("ReteFuente");

        txtICA.setEditable(false);

        txtRete.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4)
                            .addComponent(ReteFuente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(valNet, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(valTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valIva, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(icalabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtICA, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valNet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icalabel)
                    .addComponent(txtICA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReteFuente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valIva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtNombre.setEditable(false);

        jLabel8.setText("Nombre");

        factura.setEditable(false);
        factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaActionPerformed(evt);
            }
        });

        jLabel9.setText("Num Fac");

        random.setEditable(false);

        jLabel11.setText("Suerte");

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(random, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(factura, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre)
                            .addComponent(txtResp)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(random, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitActionPerformed

    private void total5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total5ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        seleccion1 = (String) jComboBox1.getSelectedItem();
        if (seleccion1.equals("--Seleccionar--")) {
            txtArt1.setText("");
        } else {
            txtArt1.setText(seleccion1);
            JComboBox[] columnas = {jComboBox2, jComboBox3, jComboBox4, jComboBox5};
            for (JComboBox box : columnas) {
                box.setModel(Con1.obt_Item());
                box.removeItem(jComboBox1.getSelectedItem());
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged

        c1 = Integer.parseInt(jSpinner1.getValue().toString());
        int val = 0;
        exi = 0;
        try {
            String sql = "SELECT prec_item, exi_item FROM productos WHERE nom_item = '" + seleccion1 + "'";
            conet = Con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            String[] usuarios = new String[2];
            while (rs.next()) {
                usuarios[0] = rs.getString("prec_item");
                usuarios[1] = rs.getString("exi_item");
            }
            val = Integer.parseInt(usuarios[0]);
            exi = Integer.parseInt(usuarios[1]);
            if (exi < c1) {
                JOptionPane.showMessageDialog(null, "cantidades insuficientes");
                jSpinner1.setValue(0);
            }
            int total = val * c1;

            total1.setText(String.valueOf(total));

            calcular();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        c2 = Integer.parseInt(jSpinner2.getValue().toString());
        int val = 0;
        exi = 0;
        try {
            String sql = "SELECT prec_item, exi_item FROM productos WHERE nom_item = '" + seleccion2 + "'";
            conet = Con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            String[] usuarios = new String[2];
            while (rs.next()) {
                usuarios[0] = rs.getString("prec_item");
                usuarios[1] = rs.getString("exi_item");
            }

            val = Integer.parseInt(usuarios[0]);
            exi = Integer.parseInt(usuarios[1]);
            if (exi < c2) {
                JOptionPane.showMessageDialog(null, "cantidades insuficientes");
                jSpinner2.setValue(0);
            }
            int total = val * c2;

            total2.setText(String.valueOf(total));
        } catch (Exception e) {
        }
        calcular();

    }//GEN-LAST:event_jSpinner2StateChanged

    private void jSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner3StateChanged
        c3 = Integer.parseInt(jSpinner3.getValue().toString());
        int val = 0;
        exi = 0;
        try {
            String sql = "SELECT prec_item, exi_item FROM productos WHERE nom_item = '" + seleccion3 + "'";
            conet = Con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            String[] usuarios = new String[2];
            while (rs.next()) {
                usuarios[0] = rs.getString("prec_item");
                usuarios[1] = rs.getString("exi_item");
            }

            val = Integer.parseInt(usuarios[0]);
            exi = Integer.parseInt(usuarios[1]);
            if (exi < c3) {
                JOptionPane.showMessageDialog(null, "cantidades insuficientes");
                jSpinner3.setValue(0);
            }
            int total = val * c3;

            total3.setText(String.valueOf(total));
            calcular();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jSpinner3StateChanged

    private void jSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner4StateChanged
        c4 = Integer.parseInt(jSpinner4.getValue().toString());
        int val = 0;
        exi = 0;
        try {
            String sql = "SELECT prec_item, exi_item FROM productos WHERE nom_item = '" + seleccion4 + "'";
            conet = Con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            String[] usuarios = new String[2];
            while (rs.next()) {
                usuarios[0] = rs.getString("prec_item");
                usuarios[1] = rs.getString("exi_item");
            }

            val = Integer.parseInt(usuarios[0]);
            exi = Integer.parseInt(usuarios[1]);
            if (exi < c4) {
                JOptionPane.showMessageDialog(null, "cantidades insuficientes");
                jSpinner4.setValue(0);
            }
            int total = val * c4;

            total4.setText(String.valueOf(total));
            calcular();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jSpinner4StateChanged

    private void jSpinner5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner5StateChanged
        c5 = Integer.parseInt(jSpinner5.getValue().toString());
        int val = 0;
        exi = 0;
        try {
            String sql = "SELECT prec_item, exi_item FROM productos WHERE nom_item = '" + seleccion5 + "'";
            conet = Con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            String[] usuarios = new String[2];
            while (rs.next()) {
                usuarios[0] = rs.getString("prec_item");
                usuarios[1] = rs.getString("exi_item");
            }

            val = Integer.parseInt(usuarios[0]);
            exi = Integer.parseInt(usuarios[1]);
            if (exi < c5) {
                JOptionPane.showMessageDialog(null, "cantidades insuficientes");
                jSpinner5.setValue(0);
            }
            int total = val * c5;

            total5.setText(String.valueOf(total));
            calcular();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jSpinner5StateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        seleccion2 = (String) jComboBox2.getSelectedItem();
        if (seleccion2.equals("--Seleccionar--")) {
            txtArt2.setText("");
        } else {
            txtArt2.setText(seleccion2);
            JComboBox[] columnas = {jComboBox3, jComboBox4, jComboBox5};
            for (JComboBox box : columnas) {
                box.removeItem(jComboBox2.getSelectedItem());
            }
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        seleccion3 = (String) jComboBox3.getSelectedItem();
        if (seleccion3.equals("--Seleccionar--")) {
            txtArt3.setText("");
        } else {
            txtArt3.setText(seleccion3);
            JComboBox[] columnas = {jComboBox4, jComboBox5};
            for (JComboBox box : columnas) {
                box.removeItem(jComboBox3.getSelectedItem());
            }
        }
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        seleccion4 = (String) jComboBox4.getSelectedItem();
        if (seleccion4.equals("--Seleccionar--")) {
            txtArt4.setText("");
        } else {
            txtArt4.setText(seleccion4);
            jComboBox5.removeItem(jComboBox4.getSelectedItem());
        }
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        seleccion5 = (String) jComboBox5.getSelectedItem();
        if (seleccion5.equals("--Seleccionar--")) {
            txtArt5.setText("");
        } else {
            txtArt5.setText(seleccion5);
        }
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        guardarFactura();
        Limpiar();
        User a = new User();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facturaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        user.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void valTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public ResultSet getConsulta() {
        return this.rs;
    }

    void actuDatosFac() {
        buscar = txtNombre.getText();
        try {
            String sql = "SELECT nit, Responsable FROM usuarios WHERE nombre= '" + buscar + "'";
            conet = Con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            String[] usuarios = new String[2];
            while (rs.next()) {
                usuarios[0] = rs.getString("nit");
                usuarios[1] = rs.getString("Responsable");
            }
            txtNit.setText(usuarios[0]);
            txtResp.setText(usuarios[1]);
        } catch (Exception e) {
        }

    }

    void calcular() {
        valTotal.setText("");
        double suert = 0;
        vtotal = Math.round((Integer.parseInt(total1.getText()) + Integer.parseInt(total2.getText())
                + Integer.parseInt(total3.getText()) + Integer.parseInt(total4.getText())
                + Integer.parseInt(total5.getText())));
        valiv = Math.round(Double.valueOf(vtotal) * 0.19);
        valica = Math.round(Double.valueOf(vtotal) * 0.04);
        valrete = Math.round(Double.valueOf(vtotal) * 0.05);
        valnet = Math.round(Double.valueOf(vtotal) - valiv - valica - valrete);

        valIva.setText(String.valueOf(Math.round(valiv)));
        valNet.setText(String.valueOf(Math.round(valnet)));
        txtICA.setText(String.valueOf(Math.round(valica)));
        txtRete.setText(String.valueOf(Math.round(valrete)));
        if (Integer.parseInt(random.getText()) == 1 || Integer.parseInt(random.getText()) == 2) {
            suert = 0.9;
            txtDesc.setText("10%");
        }
        if (Integer.parseInt(random.getText()) == 3 || Integer.parseInt(random.getText()) == 4) {
            suert = 0.8;
            txtDesc.setText("20%");
        }
        if (Integer.parseInt(random.getText()) == 5 || Integer.parseInt(random.getText()) == 6) {
            suert = 0.7;
            txtDesc.setText("30%");
        }
        if (Integer.parseInt(random.getText()) == 7 || Integer.parseInt(random.getText()) == 8) {
            suert = 0.6;
            txtDesc.setText("40%");
        }
        if (Integer.parseInt(random.getText()) == 9 || Integer.parseInt(random.getText()) == 0) {
            suert = 0.5;
            txtDesc.setText("50%");
        }
        vtotal = Math.round((valnet * suert) + valiv + valica + valrete);
        valTotal.setText(String.valueOf(Math.round(vtotal)));
    }

    void Limpiar() {
        iniciarCombobox();
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);

        total1.setText("0");
        total2.setText("0");
        total3.setText("0");
        total4.setText("0");
        total5.setText("0");

        valNet.setText("");
        valIva.setText("");
        valNet.setText("");
        valTotal.setText("");
        jSpinner1.setValue(0);
        jSpinner2.setValue(0);
        jSpinner3.setValue(0);
        jSpinner4.setValue(0);
        jSpinner5.setValue(0);
        txtArt1.setText("");
        txtArt2.setText("");
        txtArt3.setText("");
        txtArt4.setText("");
        txtArt5.setText("");

    }

    void guardarFactura() {
        String user = txtNombre.getText();
        String nit = txtNit.getText();
        String resp = txtResp.getText();
        String totalfac = valTotal.getText();
        String iva = valIva.getText();
        String neto = valNet.getText();
        String ica = txtICA.getText();
        String rete = txtRete.getText();
        try {
            conet = Con1.getConnection();
            st = conet.createStatement();
            JComboBox[] columnas = {jComboBox1, jComboBox2, jComboBox3, jComboBox4, jComboBox5};
            JSpinner[] cantidad = {jSpinner1, jSpinner2, jSpinner3, jSpinner4, jSpinner5};
            int existencia[] = new int[5];
            String sql = "insert into facturas(usu_fac, val_fac, iva, rtFuente, ica, neto,descuento) Values ('" + user + "','" + totalfac + "','" + iva + "','" + rete + "','" + ica + "','" + neto + "','" + txtDesc.getText() + "')";
            st.executeUpdate(sql);
            //linea god
            //Thread.sleep(1000);

            for (int i = 0; i < columnas.length; i++) {
                if (!columnas[i].getSelectedItem().toString().equalsIgnoreCase("--Seleccionar--")) {
                    updateQuery = "UPDATE facturas SET " + columnas[i].getSelectedItem() + "=" + cantidad[i].getValue() + " WHERE id_fac=" + (Integer.parseInt(factura.getText()));
                    st.executeUpdate(updateQuery);
                }
                
            }
            JOptionPane.showMessageDialog(null, "Factura Guardada");
            int inventario[]= new int [1];
            for (int i = 0; i < columnas.length; i++) {
                if (!columnas[i].getSelectedItem().toString().equalsIgnoreCase("--Seleccionar--")) {
                String sql1 = "SELECT exi_item FROM productos WHERE nom_item = '" + columnas[i].getSelectedItem() + "'";
                st = conet.createStatement();
                rs = st.executeQuery(sql1);
                while (rs.next()) {
                inventario[0]= rs.getInt("exi_item")- Integer.parseInt(cantidad[i].getValue().toString()); ;
            }                
                sql="UPDATE productos SET exi_item ="+inventario[0]+" WHERE nom_item = '"+ columnas[i].getSelectedItem() + "'";
                st = conet.createStatement();
                st.executeUpdate(sql);
            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "uuuuu yaba llorar " + e);
        }
    }

    void Numfatura() {
        try {
            conet = Con1.getConnection();
            st = conet.createStatement();
            // obtener contador de Facturas
            rs = st.executeQuery("SELECT COUNT(*) AS total FROM facturas;");
            while (rs.next()) {
                this.factura.setText(String.valueOf(rs.getInt("total") + 1));
            }

        } catch (Exception e) {

        }

    }

    void iniciarCombobox() {

        this.jComboBox1.setModel(Con1.obt_Item());
        this.jComboBox2.setModel(Con1.obt_Item());
        this.jComboBox3.setModel(Con1.obt_Item());
        this.jComboBox4.setModel(Con1.obt_Item());
        this.jComboBox5.setModel(Con1.obt_Item());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ReteFuente;
    private javax.swing.JTextField factura;
    private javax.swing.JLabel icalabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JTextField random;
    private javax.swing.JTextField total1;
    private javax.swing.JTextField total2;
    private javax.swing.JTextField total3;
    private javax.swing.JTextField total4;
    private javax.swing.JTextField total5;
    private javax.swing.JTextField txtArt1;
    private javax.swing.JTextField txtArt2;
    private javax.swing.JTextField txtArt3;
    private javax.swing.JTextField txtArt4;
    private javax.swing.JTextField txtArt5;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtICA;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtResp;
    private javax.swing.JTextField txtRete;
    private javax.swing.JTextField valIva;
    private javax.swing.JTextField valNet;
    private javax.swing.JTextField valTotal;
    // End of variables declaration//GEN-END:variables
}
